export const LOAD_TOP_RECIPES_SUCCESS = 'LOAD_TOP_RECIPES_SUCCESS';

export const LOAD_TOP_RECIPES_FAILURE = 'LOAD_TOP_RECIPES_FAILURE';

export const LOAD_TOP_RECIPES_REQUEST = 'LOAD_TOP_RECIPES_REQUEST';
