export const LOAD_RECIPES_SUCCESS = 'LOAD_TOP_RECIPES_SUCCESS';

export const LOAD_RECIPES_FAILURE = 'LOAD_TOP_RECIPES_FAILURE';

export const SET_LOADING = 'SET_LOADING';
export const UNSET_LOADING = 'UNSET_LOADING';

export const GET_SINGLE_RECIPE = 'GET_SINGLE_RECIPE';

export const GET_SINGLE_RECIPE_ERROR = 'GET_SINGLE_RECIPE_ERROR';

export const GET_AUTH = 'GET_AUTH';

export const GET_AUTH_ERROR = 'GET_AUTH_ERROR';
