export const LOAD_RECIPES_SUCCESS = 'LOAD_TOP_RECIPES_SUCCESS';

export const LOAD_RECIPES_FAILURE = 'LOAD_TOP_RECIPES_FAILURE';

export const SEARCH_RECIPES_SUCCESS = 'SEARCH_RECIPES_SUCCESS';

export const SET_LOADING = 'SET_LOADING';
export const UNSET_LOADING = 'UNSET_LOADING';

export const GET_SINGLE_RECIPE = 'GET_SINGLE_RECIPE';

export const GET_SINGLE_RECIPE_ERROR = 'GET_SINGLE_RECIPE_ERROR';

export const GET_AUTH = 'GET_AUTH';

export const GET_AUTH_ERROR = 'GET_AUTH_ERROR';

export const SIGN_IN_AUTH = 'SIGN_IN_AUTH';

export const SIGN_OUT = 'SIGN_OUT';

export const GET_REVIEWS = 'GET_REVIEWS';

export const GET_REVIEWS_ERROR = 'GET_REVIEWS_ERROR';

export const POST_REVIEW_REQUEST = 'POST_REVIEW_REQUEST';

export const POST_REVIEW_SUCCESS = 'POST_REVIEW_SUCCESS';

export const ADD_RECIPE = 'ADD_RECIPE';

export const ADD_RECIPE_ERROR = 'ADD_RECIPE_ERROR';

export const GET_USER_RECIPES = 'GET_USER_RECIPES';

export const GET_USER_RECIPES_ERROR = 'GET_USER_RECIPES_ERROR';
